apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghtvec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghtvec
  template:
    metadata:
      labels:
        app: ghtvec
    spec:
      containers:
      - image: okteto.dev/ghtvec:latest
        name: ghtvec
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "78121ffa-bf94-4b90-9a82-5b197e03e20f"
        - name: Vless_Path
          value: "/vl5df6r7555"
        - name: Vmess_UUID
          value: "78121ffa-bf94-4b90-9a82-5b197e03e20f"
        - name: Vmess_Path
          value: "/vm65767rtr666"
        - name: Share_Path
          value: "/v2link"
